CREATE TABLE 'runs' (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "RunNo" TEXT NOT NULL,
    "iRunNo" INTEGER NOT NULL,
    "Comment" TEXT,
    "ObsRecs" INTEGER,
    "Individuals" INTEGER,
    "Model" TEXT,
    "ModelMD5" TEXT,
    "CtlFile" TEXT,
    "CtlFileMD5" TEXT,
    "DataFile" TEXT,
    "DataFileMD5" TEXT,
    "OutputFile" TEXT,
    "OutputFileMD5" TEXT,
    "MSF" TEXT,
    "MSFMD5" TEXT,
    "FitFile" TEXT,
    "FitFileMD5" TEXT,
    "patab" TEXT,
    "patabMD5" TEXT,
    "sdtab" TEXT,
    "sdtabMD5" TEXT,
    "catab" TEXT,
    "catabMD5" TEXT,
    "cotab" TEXT,
    "cotabMD5" TEXT,
    "mutab" TEXT,
    "mutabMD5" TEXT,
    "mytab" TEXT,
    "mytabMD5" TEXT,
	"txt" TEXT,
	"txtMD5" TEXT,
	"ext" TEXT,
	"extMD5" TEXT,
	"cov" TEXT,
	"covMD5" TEXT,
	"cor" TEXT,
	"corMD5" TEXT,
	"coi" TEXT,
	"coiMD5" TEXT,
	"phi" TEXT,
	"phiMD5" TEXT,
    "cwtab" TEXT,
    "cwtabMD5" TEXT,
    "cwtabEst" TEXT,
    "cwtabEstMD5" TEXT,
    "cwtabDeriv" TEXT,
    "cwtabDerivMD5" TEXT,
    "Comments" BLOB,
    "ParentNo" TEXT,
    "KeyRun" INTEGER,
    "Timestamp" INTEGER,
    "User" TEXT
);
CREATE INDEX "runno" on 'runs' (RunNo ASC, iRunNo ASC);
CREATE INDEX "irunno" on 'runs' (iRunNo ASC);
CREATE INDEX "runno2" on 'runs' (RunNo ASC);
CREATE TABLE "thetas" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "RunNo" TEXT NOT NULL,
    "EstNo" TEXT NOT NULL,
    "Theta" INTEGER NOT NULL,
    "ThetaLabel" TEXT,
    "ThetaValue" REAL,
    "ThetaSE" REAL,
    "Lower" REAL,
    "Initial" REAL,
    "Upper" REAL,
    "ThetaRSE" REAL,
    "Model" TEXT,
    "ThetaMatrix" BLOB,
    "ThetaSigDig" REAL,
    "ThetaCIs" TEXT,
    "ThetaCIUpper" REAL,
    "ThetaCILower" REAL,
    "Timestamp" INTEGER,
    "User" TEXT
);
CREATE INDEX "thetaID" on thetas (ID ASC);
CREATE INDEX "theta" on thetas (Theta ASC);
CREATE INDEX "runno.theta" on thetas (RunNo ASC, EstNo ASC);
CREATE TABLE "omegas" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "RunNo" TEXT NOT NULL,
    "EstNo" INTEGER NOT NULL,
    "Omega" INTEGER NOT NULL,
    "OmegaValue" REAL,
    "EtaBar" REAL,
    "EtaBarSE" REAL,
    "EtaPVal" REAL,
    "OmegaInit" REAL,
    "OmegaSE" REAL,
    "OmegaRSE" REAL,
    "OmegaLabel" TEXT,
    "OmegaModel" TEXT,
    "OmegaMatrix" BLOB,
    "OmegaSigDig" REAL,
    "Blocks" INTEGER,
    "OmegaCIs" TEXT,
    "OmegaCIUpper" REAL,
    "OmegaCILower" REAL,
    "OmegaPerc" REAL,
    "EtaShrinkage" REAL,
    "Timestamp" INTEGER,
    "User" TEXT
);
CREATE INDEX "omega" on omegas (Omega ASC);
CREATE INDEX "runno.omega" on omegas (RunNo ASC, EstNo ASC);
CREATE INDEX "omegaID" on omegas (ID ASC);
CREATE TABLE sigmas (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "RunNo" TEXT,
    "EstNo" INTEGER,
    "Sigma" INTEGER,
    "SigmaValue" REAL,
    "SigmaInit" REAL,
    "SigmaSE" REAL,
    "SigmaRSE" REAL,
    "SigmaLabel" TEXT,
	"SigmaModel" TEXT,
    "SigmaMatrix" BLOB,
    "SigmaSigDig" REAL,
    "Blocks" INTEGER,
    "SigmaCIs" TEXT,
    "SigmaCIUpper" REAL,
    "SigmaCILower" REAL,
    "EpsilonShrinkage" REAL,
    "Timestamp" INTEGER,
    "User" TEXT
);
CREATE UNIQUE INDEX "sigmaID" on sigmas (ID ASC);
CREATE UNIQUE INDEX "sigma" on sigmas (Sigma ASC);
CREATE UNIQUE INDEX "runno.sigma" on sigmas (RunNo ASC, EstNo ASC);
CREATE TABLE "trans" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Action" TEXT,
    "RunNo" TEXT,
    "Timestamp" INTEGER,
    "User" TEXT
);
CREATE INDEX "transID" on trans (ID ASC);
CREATE INDEX "main" on trans (Timestamp ASC, RunNo ASC);
CREATE TABLE est (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "RunNo" TEXT,
    "EstID" INTEGER,
    "Method" TEXT,
    "MethLong" TEXT,
	"GoalFunction" TEXT,
    "OFV" REAL,
    "dOFV" REAL,
    "ParentNo" TEXT,
    "KeyEst" INTEGER,
    "MinShort" TEXT,
    "Minimization" BLOB,
    "FnEvals" INTEGER,
    "SigDigits" TEXT,
	"SIGL" INTEGER,
	"TOL" INTEGER,
	"NSIG" INTEGER,
    "NIter" INTEGER, 
	"ISample" INTEGER, 
	"ISampleM1" INTEGER,
	"ISampleM2" INTEGER,
	"ISampleM3" INTEGER,
	"IAccept" REAL, 
	"PSampleM1" INTEGER,
	"PSampleM2" INTEGER,
	"PSampleM3" INTEGER,
	"PAccept" REAL, 
	"OSampleM1" INTEGER,
	"OSampleM2" INTEGER,
	"OAccept" REAL, 
	"DF" REAL, 
	"Seed" INTEGER, 
	"NBurn" REAL,
    "CovStep" BLOB,
    "CovShort" TEXT,
    "CondEst" INTEGER,
    "CenteredEta" INTEGER,
    "Interaction" INTEGER,
    "Laplacian" INTEGER,
    "Comments" BLOB,
    "OmegaInitMatrix" BLOB,
    "SigmaInitMatrix" BLOB,
    "OmegaMatrix" BLOB,
    "SigmaMatrix" BLOB,
    "OmegaSEMatrix" BLOB,
    "SigmaSEMatrix" BLOB,
    "CovMatrix" BLOB,
    "CorrMatrix" BLOB,
    "InvCovMatrix" BLOB,
    "Eigenvalues" BLOB,
    "ConditionNumber" REAL,
    "Warnings" TEXT,
    "Timestamp" INTEGER,
    "User" TEXT
);
CREATE INDEX "estID" on est (ID ASC);
CREATE INDEX "runno.est" on est (RunNo ASC, EstID ASC);
