<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Census.Domain\Census.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>

</Project>
